#endpoints:
#  enabled: false
info:
  component: prueba-tecnica
spring:
  application:
    name: prueba-tecnica
  profiles:
    active: dev
  datasource:
    postgresql:
      url: jdbc:postgresql://localhost:5432/test_quind_bd
      driverClassName: org.postgresql.Driver
      username: prueba
      password: pruebapass
  jpa:
    postgresql:
      databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  servlet:
    context-path: "/prueba-tecnica"
  port: 8181

api:
  notification:
    urlNotification: "http://localhost:8080/marketing-notifications/api/v1/notifications/"
    uriMessage: "send/message"
    maxAttempts: 3
    minBackoffSeconds: 2